# Generated by Django 5.0.2 on 2024-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.CharField(max_length=200, verbose_name='Описание')),
                ('text', models.TextField(max_length=1000, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='news/static/news/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
