# Generated by Django 5.0.2 on 2024-04-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_remove_cartitem_size_cartitem_name_delete_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='name',
            new_name='size',
        ),
    ]
