# Generated by Django 5.0.2 on 2024-04-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_rename_name_cartitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
