# Generated by Django 5.0.2 on 2024-05-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_remove_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='adress',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3, verbose_name='Размер'),
        ),
    ]
