# Generated by Django 5.0.2 on 2024-03-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_albums_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на альбом soundcloud'),
        ),
        migrations.AddField(
            model_name='albums',
            name='spotify',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на альбом spotify'),
        ),
        migrations.AddField(
            model_name='albums',
            name='vk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на альбом vk'),
        ),
    ]
