# Generated by Django 5.0.2 on 2024-03-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_albums_soundcloud_albums_spotify_albums_vk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='soundcloud',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='vk',
        ),
    ]
