# Generated by Django 5.0.2 on 2024-04-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
