# Generated by Django 5.0.2 on 2024-04-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_chat_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
