# Generated by Django 5.0.2 on 2024-04-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/avatar.jpg', null=True, upload_to='ForumProfile/static/ForumProfile/'),
        ),
    ]
