# Generated by Django 5.0.2 on 2024-04-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumProfile', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
