# Generated by Django 5.0.2 on 2024-03-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('date', models.DateField(verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
            },
        ),
    ]
